[package]
name = "rut-server-rust"
version = "0.0.1"
authors = ["DLuo"]

[[test]]
name = "tests"
path = "tests/lib.rs"

[dependencies]
futures = "0.1.25"
actix = "0.7.9"
actix-web = "0.7.19"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
diesel = { version = "1.4.2", features = ["postgres","chrono","serde_json", "r2d2"] }
postgres = {version= "0.15.2", features = ["with-chrono"]}
uuid = { version = "0.7.4", features = ["serde", "v4"] }
deunicode = "1.0.0"
jsonwebtoken = "5.0.1"
num_cpus = "1.10.0"
chrono = { version = "0.4.6", features = ["serde"] }
bcrypt = "0.3.0"
dotenv = "0.13.0"
log = "0.4.6" 
env_logger = "0.6.1"
base64 = "0.10.1"
regex = "1.1.3"
lazy_static = "1.3.0"

# openssl = "0.10.20"
