[package]
name = "rut-server-rust"
version = "0.0.2"
edition = "2018"
authors = ["DLuo"]

[[test]]
name = "tests"
path = "tests/lib.rs"

[dependencies]
futures = "0.1.26"
actix = { version = "0.8.1", features = ["http"] }
actix-rt = "0.2.2"
actix-web = "1.0.0-alpha.6"
diesel = { version = "1.4.2", features = ["postgres","chrono","serde_json","uuidv07","r2d2"] }
r2d2 = "0.8.4"
serde_derive="1.0.90"
serde_json="1.0"
serde="1.0"
jsonwebtoken = { git = "https://github.com/Keats/jsonwebtoken.git", branch = "next" }

derive_more = "0.14"
regex = "1.1.6"
lazy_static = "1.3.0"
uuid = { version = "0.7.4", features = ["serde", "v4"] }
deunicode = "1.0.0"
bcrypt = "0.4.0"
chrono = { version = "0.4.6", features = ["serde"] }
env_logger = "0.6.1"
dotenv = "0.13.0"
base64 = "0.10.1"
num_cpus = "1.10.0"

# openssl = "0.10.20"
