[package]
name = "rut-server-rust"
version = "0.0.1"
authors = ["DLuo"]

[[test]]
name = "tests"
path = "tests/lib.rs"

[dependencies]
futures = "0.1.25"
actix = "0.7.9"
actix-web = { version = "0.7.18",  default-features = false }
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.35"
diesel = { version = "1.3.3", features = ["postgres","chrono","serde_json", "r2d2"] }
postgres = {version= "0.15.2", features = ["with-chrono"]}
regex = "1.1.0"
jsonwebtoken = "5.0.1"
bytes = "0.4.11"
chrono = { version = "0.4", features = ["serde"] }
timeago = "0.1.5"
dotenv = "0.13.0"
env_logger = "0.6.0"
openssl = "0.10"
bcrypt = "0.2.1"
md5 = "0.6.1" 
ring = "0.13.5"
num_cpus = "1.9.0"